version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: dhfai-container
    restart: always
    environment:
      POSTGRES_USER: dhfai
      POSTGRES_PASSWORD: dhfai
      POSTGRES_DB: rpp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: